apiVersion: v1
kind: Pod
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  containers:
  - name: test
    image: asia-southeast2-docker.pkg.dev/alevz-demo-1/containers/svc1:latest
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: LoadBalancer
  selector:
    app: svc1
  ports:
  - name: http
    port: 80
    targetPort: 8080
